global using Dry.Admin.Application.Contracts.Dtos;
global using Dry.Admin.Application.Contracts.Services;
global using Dry.Admin.Domain;
global using Dry.Admin.EF.Sqlite;
global using Dry.Application.RESTFul.Api;
global using Dry.AspNetCore;
global using Dry.AspNetCore.Infrastructure;
global using Dry.AspNetCore.Infrastructure.AppBuilderConfigure;
global using Dry.AspNetCore.Infrastructure.AppConfigure;
global using Dry.AspNetCore.Infrastructure.AppExceptionHandle;
global using Dry.AspNetCore.Infrastructure.RequestActionExecute;
global using Dry.AspNetCore.Infrastructure.RequestResourceExecute;
global using Dry.AspNetCore.Infrastructure.RequestResultExecute;
global using Dry.AutoMapper;
global using Dry.Core.Json;
global using Dry.Dependency;
global using Dry.EF.Extensions;
global using Dry.Serilog.Extensions;
global using Dry.Swagger;
global using MediatR;
global using Microsoft.AspNetCore.Hosting;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;

var app = await WebAppHelper.CreateAsync(args);
await app.RunAsync();