global using Dry.Core.Model;
global using Dry.Domain.Contexts;
global using Dry.Domain.Entities;
global using Dry.Domain.Queryables;
global using Dry.Domain.Repositories;
global using Dry.Domain.Shared;
global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using System.Linq.Expressions;