// <auto-generated />
using System;
using Dry.Admin.EF.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dry.Admin.EF.Sqlite.Migrations
{
    [DbContext(typeof(AdminDbContext))]
    [Migration("20201202063203_1.0.0.0")]
    partial class _1000
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6");

            modelBuilder.Entity("Dry.Admin.Domain.Entities.Application", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .HasAnnotation("DbDescription", "系统id");

                    b.Property<DateTime>("AddTime")
                        .HasColumnType("TEXT")
                        .HasAnnotation("DbDescription", "添加时间");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasAnnotation("DbDescription", "说明");

                    b.Property<bool>("Enable")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("DbDescription", "是否可用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(50)
                        .HasAnnotation("DbDescription", "名称");

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(200)
                        .HasAnnotation("DbDescription", "Secret");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER")
                        .HasAnnotation("DbDescription", "类型");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasAnnotation("DbDescription", "地址");

                    b.HasKey("Id");

                    b.HasIndex("AddTime");

                    b.ToTable("Application");

                    b.HasAnnotation("DbDescription", "审核流程");
                });
#pragma warning restore 612, 618
        }
    }
}
